[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
server = { path = "../server" }
thiserror = "2"
clap = { version = "4", features = ["derive"] }
ctrlc = "3.5.1"
log.workspace = true
env_logger.workspace = true
